In [1]:
import tensorflow as tf

In [ ]:
def Loss_Arcface(embedding, labels, out_num, s=64., m=0.5, name='arcface'):    
    """
    embedding: the input embedding vectors
    labels: the input labels, the shape should
    s: scalar value default is 64
    out_num: output class num
    m: the margin value, default is 0.5
    return the final calculated output, this output is send into the tf.nn.softmax directly
    """
    

In [2]:
indices= tf.constant([[0], [2]])

In [3]:
indices.shape

TensorShape([Dimension(2), Dimension(1)])

In [4]:
indices

<tf.Tensor 'Const:0' shape=(2, 1) dtype=int32>

In [5]:
updates = tf.constant([[[5, 5, 5, 5], [6, 6, 6, 6], [7, 7, 7, 7], [8, 8, 8, 8]],
                      [[5, 5, 5, 5], [6, 6, 6, 6], [7, 7, 7, 7], [8, 8, 8, 8]]])

In [6]:
updates.shape

TensorShape([Dimension(2), Dimension(4), Dimension(4)])

In [15]:
shape = tf.constant([4, 4, 4])

In [16]:
shape.shape

TensorShape([Dimension(3)])

In [17]:
scatter = tf.scatter_nd(indices, updates, shape)

In [18]:
scatter.shape

TensorShape([Dimension(4), Dimension(4), Dimension(4)])

In [19]:
with tf.Session() as sess:
    print(sess.run(scatter))

[[[5 5 5 5]
  [6 6 6 6]
  [7 7 7 7]
  [8 8 8 8]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[5 5 5 5]
  [6 6 6 6]
  [7 7 7 7]
  [8 8 8 8]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
